### ISSUE TITLE
Omit doesn't accept numeric keys

### ISSUE THREAD

**Issue by jBerling** [guigrpa/timm#10]
I know we are not supposed to pass in numbers as keys, according to the signature, but it would be nice to be able to do so. Current behavior: `omit({0: 'a'}, 0)` => `{0: 'a'}`.

**Comment by guigrpa** [comment]
Sorry for the late reply! 

I see two options there:

1. Either convert the numeric key to string before calling `omit()` (avoids introducing extra checks and performance penalties in `omit()`)
2. Use an array (probably better if you are using numeric keys) and use timm's `removeAt()`

Would any of these apply to your use case?

**Comment by jBerling** [comment]
I agree it's more in line with JavaScript to not use numerical keys. 10 days ago I wrongly thought objects accepted strings and numbers as keys, but a nice colleague informed me I was wrong.

Anyway, in flow you can type your keys to be numbers (`{[number]: any}`) and `({ 4 : "foo" })[4] // => "foo"`, so you could argue it would be less surprising if `omit({0: 'a'}, 0) // => {}` would work too.

But I fully understand if you don't agree.

**Comment by guigrpa** [comment]
I think it is better if we don't add implicit type casts, given that object keys will be strings in any case (even if they can be typed in flow differently). Thanks in any case for your suggestion!
