### ISSUE TITLE
Consider adding development mode

### ISSUE THREAD

**Issue by dentrado** [guigrpa/timm#11]
From the Readme:
> Important notice: timm does not freeze the objects it provides. In other words, it doesn't protect you against inadvertently modifying them in your code. I considered deeply freezing all objects with Object.freeze(), but it is really slow. Then I considered doing this only in development (like seamless-immutable), but then modifying frozen objects will silently fail in development (unless you use strict in your code), and –worse still– succeed in production. Not good. In conclusion, be careful (or send me a suggestion to work around this!).

I agree it wouldn't be good to use a development version with Object.freeze() without "use strict", however it's easy to enforce "use strict" everywhere in your code if you use a transpiler like eg. babel, ([transform-strict-mode](https://babeljs.io/docs/plugins/transform-strict-mode/) is even enabled by default in the "es2015" preset) so I think it would still be a very useful thing to have.

**Comment by guigrpa** [comment]
I'd suggest wrapping the timm functions you use, something like this:

```js
import { merge as _merge } from 'timm';

const merge = (a, ...rest) => {
  const out = _merge(a, ...rest);
  return out === a || process.env.NODE_ENV === 'production'
    ? out
    : Object.freeze(a);
}

export { merge };
```

We omit the freezing operation if timm returned the unmodified input, or if we're running in production.

You could then using these wrappers instead of timm's original functions in `use strict`-enabled code. What do you think?

**Comment by dentrado** [comment]
Yes that could work, I'm also starting to think it would be enough to do a deepFreeze on some specific places in my code where I want to make sure nothing is mutated. Thanks!

**Comment by guigrpa** [comment]
Thanks to you for the idea!
