### ISSUE TITLE
Is it faster than immutability-helper?

### ISSUE THREAD

**Issue by deser** [guigrpa/timm#18]
Seems both Immutable.js and immutability-helper do copy via Object.create. Isn't it faster than your clone?

**Comment by guigrpa** [comment]
I haven't benchmarked it against immutability-helper, but please fill free to suggest (or contribute!) solutions which you find to be better/faster or with (even) less user friction. Thanks!

**Comment by guigrpa** [comment]
Also feel free to improve timm's benchmarks by including additional libraries to compare with!

**Comment by deser** [comment]
Ok, thanks!

**Comment by guigrpa** [comment]
@danro Done, I look forward to the inclusion of immutability-helper! ;)
