### ISSUE TITLE
support/fix es6 module

### ISSUE THREAD

**Issue by dantman** [guigrpa/timm#19]
The `timm/lib/timm_es6` module referenced by the README does not exist in the package.

I see the following in the `timm@1.4.1` release on npm:

- lib/timm.js
- lib/timm.js.flow
- lib/timm.min.js
- src/api.js.flow
- src/timm.js

I don't see any es6 modules only version.

Perhaps it would be a good idea to add a new modules-only build and use the `"module"` field supported by WebPack and rollup to refer to it.

**Comment by guigrpa** [comment]
I'd rather not add new build options, until the situation with respect to modules becomes clearer. In fact, I've removed the reference to the missing file, thanks for pointing it out!
