### ISSUE TITLE
Create a pop() or removeLast()

### ISSUE THREAD

**Issue by marchaos** [guigrpa/timm#2]
Hey, 

minor change, but it would be nice to have a removeLast() to compliment addLast() for a pop() like operation. 

Cheers, 
Marc.

**Comment by guigrpa** [comment]
Working on it!

**Comment by guigrpa** [comment]
Finally chose the names `removeFirst()` and `removeLast()`. Released in v1.2.0 (4ec839a)

**Comment by marchaos** [comment]
Thanks! Will update to the latest.
