### ISSUE TITLE
mergeDeep does not behave as documented

### ISSUE THREAD

**Issue by gkaemmer** [guigrpa/timm#20]
Hello! Running into a small issue with timm.

The documentation states that `mergeDeep` treats `undefined` and `null` the same way. In other words, it says `mergeDeep` will not overwrite a property with `null`, but it seems to do so.
```
mergeDeep({ hello: { world: '123' } }, { hello: { world: null } }) // => { hello: { world: null } }
mergeDeep({ hello: { world: '123' } }, { hello: { world: undefined } }) // => { hello: { world: '123' } }

mergeDeep({ hello: '123' }, { hello: null }) // => { hello: null }
mergeDeep({ hello: '123' }, { hello: undefined }) // => { hello: '123' }
```

Is this expected? Or a bug?

**Comment by guigrpa** [comment]
Thanks for the clear report. Indeed, it looks like a bug. Care to submit a PR? Even if it's only a test case, it'd be useful!

**Comment by guigrpa** [comment]
(Sorry if my previous response reached you, I hadn't read the issue correctly). In fact, it's by design: `null` is considered a normal value, whereas `undefined` is the lack of a value —hence, it causes no update...

**Comment by guigrpa** [comment]
Maybe the docs are wrong. Can you indicate where it says that both values are treated equal?

**Comment by gkaemmer** [comment]
Gotcha. The the `mergeDeep` section of the README (as I read it) says that `null` and `undefined` are treated the same:

> The unmodified obj1 is returned if obj2 does not provide something new to obj1, i.e. if either of the following conditions are true:
>
> - **obj2 is null or undefined**
> - obj2 is an object, but it is empty
> - All attributes of obj2 are referentially equal to the corresponding attributes of obj

**Comment by guigrpa** [comment]
I'm afraid I disagree. If `obj2` **itself** is `undefined` or `null`, the same object is returned (see [this test](https://github.com/guigrpa/timm/blob/master/test/objects.js#L269) and [this one](https://github.com/guigrpa/timm/blob/master/test/objects.js#L286), respectively).

Another thing is that an attribute of `obj2` are `null` (in which case [it is applied](https://github.com/guigrpa/timm/blob/master/test/objects.js#L286)) or `undefined` (in which case [it is ignored](https://github.com/guigrpa/timm/blob/master/test/objects.js#L274)). Maybe this is not well reflected in the last bullet. Instead of:

> All attributes of `obj2` are referentially equal to the corresponding attributes of `obj`

…it should probably say:

> All attributes of `obj2` are either `undefined` or referentially equal to the corresponding attributes of `obj`

What do you think?

**Comment by gkaemmer** [comment]
I think in the case of `mergeDeep` it's a little less clear, because I'd expect that every comparison uses `mergeDeep` recursively. Therefore, if `null` and `undefined` are treated the same at the top level, they should be treated the same down the tree.

In other words, given the current implementation, I'd think that `mergeDeep('123', null)` should return `null`, because that's consistent with what happens one and more levels deep in the tree.

**Comment by gkaemmer** [comment]
I'll close this, because I don't think I can actually solve my issue with timm (I'll have to explicitly remove null values in my case), but it might be something to consider.
