### ISSUE TITLE
`merge` function seems to no longer be variadic

### ISSUE THREAD

**Issue by jjhbw** [guigrpa/timm#37]
Hi!

After updating the `timm` dependency of `docx-templates` to `1.7.0`, I get:
```
src/jsSandbox.ts:28:5 - error TS2554: Expected 1-3 arguments, but got 4.

28     ctx.options.additionalJsContext
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This happens in a piece of code that you may be familiar with ;)

```typescript
  // Retrieve the current JS sandbox contents (if any) and add
  // the code to be run, and a placeholder for the result,
  // as well as all data defined by the user
  const sandbox: { [ind: string]: any } = merge(
    ctx.jsSandbox || {},
    {
      __code__: code,
      __result__: undefined,
    },
    data,
    ctx.options.additionalJsContext
  );
```
I think something may have gone wrong with the type definitions.

**Comment by guigrpa** [comment]
It looks like the TypeScript overloads for `merge()` did not consider all cases. Could you please try with v1.7.1? Thanks for reporting!

**Comment by jjhbw** [comment]
Awesome, v1.7.1 does the trick. Thanks!
