### ISSUE TITLE
SetIn returns type is "unknown"

### ISSUE THREAD

**Issue by marchaos** [guigrpa/timm#38]
Not sure what the reasoning for this is, but I would imagine that setIn should return the type of object that you pass in, rather than "unknown"

**Comment by guigrpa** [comment]
Well, I `setIn()` can modify the type of the input object:

`setIn({ qat: { foo: 'bar' }, qux: 3 }, ['qat', 'foo'], 3)`

There are just too many different cases, so I believe the only way to be type-safe is to define the output as `unknown`. But suggestions are welcome!

In your case, maybe you can do something like:

```js
const a = { foo: 'bar', wee: 'wat' }
const b = setIn(a, ['foo'], 'bat') as typeof a;
```
