### ISSUE TITLE
Would like to modify your benchmarks and reference in my own project

### ISSUE THREAD

**Issue by engineforce** [guigrpa/timm#5]
Hi Guillermo,

I like your benchmarks tool for immutable libraries from [timm](https://github.com/guigrpa/timm), and I would like to modify it and references in my own GitHub project. Is it OK?

**Comment by guigrpa** [comment]
Do you mean you want to submit a PR to include your own library as a devDependency and in the benchmark tool?

**Comment by engineforce** [comment]
Hi Guillermo,

Just want to notify you I have copied your benchmarks.js (output from benchmarks.coffee), and modified for my own immutable libraries, which is located at https://github.com/engineforce/ImmutableAssign/blob/master/debug/benchmarks.js.

**Comment by guigrpa** [comment]
@engineforce Thanks for the info! It would be great if you also include Timm's performance in the benchmark. Thanks!
