### ISSUE TITLE
performance test in jsfiddle

### ISSUE THREAD

**Issue by ronniegong** [guigrpa/timm#6]
test seamless-immutable setIn/merge with very deep object in jsfiddle

even use the seamless-immutable development version, it's quick, nearly 3-5 ms

is there anything wrong?

https://jsfiddle.net/fymssbfq/

**Comment by iotch** [comment]
Have you tried to run it 200k times?

> Feel free to run them yourself (download the repo and then npm install && npm run benchmarks). These are my results on a Windows machine for **200k** iterations (Node v6.2.0)

Here is the updated version of the fiddle, but with only 10k iterations (as 200k will likely freeze the browser)
https://jsfiddle.net/Lu2py0wg/

**Comment by ronniegong** [comment]
i see,thanks
